### ISSUE TITLE
Setting up xonda with conda 4.4.x

### ISSUE THREAD

**Issue by shoyer** [gforsyth/xonda#31]
I'm struggling to setup xonda with conda 4.4.x.

When I try `conda activate`, I get
`CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.`]]

Should I still be adding `~/miniconda3/bin` to path? The latest versions of conda no longer recommend this. For context:
https://conda.io/docs/release-notes.html#recommended-change-to-enable-conda-in-your-shell

**Comment by shoyer** [comment]
I'm guessing that my trouble is that I didn't install xonsh with conda (I used brew on OS X instead). `import conda` fails with `ImportError`.

Would the golden path be to reinstall xonsh from conda?

**Comment by gforsyth** [comment]
Hey @shoyer -- thanks for pointing out the changelist, I haven't been keeping close enough attention to the internal workings of `conda`.  
For now, you should still add your `miniconda3/bin` to your path. The `xonda` activate functionality is different from the old `conda` style and it pops the `miniconda3/bin` off of your `$PATH` before adding the new environment to avoid having both the environment and the base on `$PATH` at the same time.  I think this is probably what they were trying to avoid with the new behavior in `conda`.  
In any case, I've been using the updated version with `xonda` for a few weeks now and it has worked without any problems (but I have kept `miniconda3/bin` at the front of my `$PATH`). 

As to your second comment, yeah, it's almost certainly `brew` causing trouble.  `brew` sandboxes `xonsh` and makes it trickier to install packages into that environment.  
You can either install `xonsh` using `pip` or `conda` into your miniconda base environment, or alternatively, there is an `xpip` command in `xonsh` that uses `pip` to always install something into the `site-packages` that `xonsh` is looking at.  (it also may be called `xip` if you are on `xonsh<0.6.0`)  That, however, won't work for `conda`, I don't think, since the pypi `conda` package isn't really a functional `conda`, so far as I know.

Let me know if you hit any more snags.

**Comment by shoyer** [comment]
OK, things are working great after I reinstalled xonsh using conda.

It might be worth noting something about this in the readme for this package and/or adding a check when xonda is installed to make sure conda is available. In retrospect, it makes a lot of sense that xonda needs to have conda installed in xonsh's environment, but this wasn't entirely obvious to me from the error messages I saw.

**Comment by gforsyth** [comment]
Great! And yes, I agree about the need for more documentation and better
error checking.

**Comment by gforsyth** [comment]
Addressed in #32 and #35
